name: Main

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: gecko-extract-linux-x64
            rid: linux-x64
          - os: windows-latest
            artifact_name: gecko-extract-win-x64.exe
            ext: .exe
            rid: win-x64
          - os: macos-latest
            artifact_name: gecko-extract-osx-x64
            rid: osx-x64

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: Publish
        run: dotnet publish -c release -r ${{ matrix.rid }} -o bin/release/${{ matrix.os }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/release/${{ matrix.os }}/intouch${{ matrix.ext }}
          asset_name: ${{ matrix.artifact_name }}
          tag: ${{ github.ref }}
          overwrite: true
